hl.config({ autogenerated = false })

hl.env("UV_PROJECT_ENVIRONMENT", ".venv")
hl.env("DMS_DANKBAR_LAYER", "overlay")
hl.env("DMS_HIDE_TRAYIDS", "spotify")
hl.env("QS_ICON_THEME", "Adwaita")

hl.config({
  general = {
    gaps_in = 5,
    gaps_out = 10,
    border_size = 2,
  },
  misc = {
    disable_hyprland_logo = true,
    disable_splash_rendering = true,
    force_default_wallpaper = 0,
  },
  input = {
    follow_mouse = 1,
    numlock_by_default = true,
    kb_layout = "gb",
    kb_variant = "colemak",
    resolve_binds_by_sym = true,
    touchpad = {
      natural_scroll = false,
      disable_while_typing = false,
      tap_to_click = false,
    },
  },
  decoration = {
    rounding = 10,
    blur = {
      enabled = true,
      size = 3,
      passes = 1,
    },
    shadow = {
      enabled = true,
      range = 4,
      render_power = 3,
    },
  },
  layout = {
    single_window_aspect_ratio = { 16, 9 },
    single_window_aspect_ratio_tolerance = 0.1,
  },
  xwayland = {
    force_zero_scaling = true,
    enabled = true,
  },
  binds = {
    scroll_event_delay = 0,
  },
})

hl.device({
  name = "keychron-keychron-v6-max",
  kb_layout = "gb",
  kb_variant = "",
  resolve_binds_by_sym = true,
})

hl.device({
  name = "keychron--keychron-link--keyboard",
  kb_layout = "gb",
  kb_variant = "",
  resolve_binds_by_sym = true,
})

hl.on("hyprland.start", function()
  local variant = ""
  if nix.xwayland.variant ~= "" then
    variant = " -variant " .. nix.xwayland.variant
  end

  hl.exec_cmd(nix.pkgs.setxkbmap .. " -layout " .. nix.xwayland.layout .. variant)
  hl.exec_cmd("uwsm app -- spotify", { workspace = "9 silent" })
  hl.exec_cmd("uwsm app -- discord", { workspace = "9 silent" })
end)
