scheme: "TrainerDex Dark"
author: "Jay Turner"
variant: "dark"
base00: "16181d"
base01: "20232b"
base02: "343a4a"
base03: "4a5264"
base04: "9ba5b4"
base05: "f2f2f2"
base06: "fafbfc"
base07: "ffffff"
base08: "e76f7c"
base09: "f4a261"
base0A: "e9c46a"
base0B: "a8c686"
base0C: "70c6d4"
base0D: "ca3755"
base0E: "b69be8"
base0F: "e07aa8"
